### ISSUE TITLE
TypeError: argument of type 'WindowsPath' is not iterable

### ISSUE THREAD

**Issue by meijiashu** [tiankuan93/ComfyUI-V-Express#11]
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cuda_setup\paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
!!! Exception during processing!!! argument of type 'WindowsPath' is not iterable
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-V-Express\nodes.py", line 345, in load_vexpress_pipeline
    v_express_pipeline = VExpressPipeline(
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-V-Express\src\pipelines\v_express_pipeline.py", line 105, in __init__
    self.register_modules(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 569, in register_modules
    not_compiled_module = _unwrap_model(module)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 286, in _unwrap_model
    from peft import PeftModel
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .auto import (
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\auto.py", line 31, in <module>
    from .config import PeftConfig
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\config.py", line 23, in <module>
    from .utils import CONFIG_NAME, PeftType, TaskType
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\utils\__init__.py", line 21, in <module>
    from .loftq_utils import replace_lora_weights_loftq
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\utils\loftq_utils.py", line 35, in <module>
    import bitsandbytes as bnb
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\autograd\_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.py", line 41, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.py", line 37, in get_instance
    cls._instance.initialize()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.py", line 31, in initialize
    self.lib = ct.cdll.LoadLibrary(binary_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'WindowsPath' is not iterable

**Comment by tiankuan93** [comment]
It seems as if there is something wrong with the environment.
