### ISSUE TITLE
Import issues - Diffusers

### ISSUE THREAD

**Issue by AILova** [tiankuan93/ComfyUI-V-Express#8]
I thought I installed everything correctly, but when I launch ComfyUI, it throws the following error about diffusers not being found.  I did a pip install -r requirements.txt and if I go to pythob command link and type "import diffusers" it successfully imports.  Anyone know what I'm doing wrong in order for this custom_node to find my installed requirements?  Thanks!

Traceback (most recent call last):
  File "F:\AI_TOOLS\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\AI_TOOLS\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-V-Express\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\AI_TOOLS\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-V-Express\nodes.py", line 12, in <module>
    from diffusers.utils.torch_utils import randn_tensor
ModuleNotFoundError: No module named 'diffusers'

**Cannot import F:\AI_TOOLS\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-V-Express module for custom nodes: No module named 'diffusers'**

**Comment by tiankuan93** [comment]
If you are using `ComfyUI_windows_portable `, you should use `.\python_embeded\python.exe -m pip` to replace `pip` for installation.

**Comment by AILova** [comment]
Thanks much for the response... I'll give it a shot.
